/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 5.1.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

export let options = {
    stages: [
        { duration: '30s', target: 20 },
        { duration: '1m30s', target: 20 },
        { duration: '20s', target: 0 },
    ],
    thresholds: {
        http_req_failed: ['rate<0.01'],
        http_req_duration: ['p(95)<100']
    }
};


const BASE_URL = "http://localhost:8080";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/node", () => {
        let url = BASE_URL + `/node`;
        // Request No. 1
        let response = http.get(url);
        check(response, {
            "OK": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
}
